const ModalType = {
    EDIT_MOVIE_OPEN: "EDIT_MOVIE_OPEN",
    EDIT_MOVIE_CLOSE: "EDIT_MOVIE_CLOSE",

    DELETE_MOVIE_OPEN: "DELETE_MOVIE_OPEN",
    DELETE_MOVIE_CLOSE: "DELETE_MOVIE_CLOSE",

    ADD_MOVIE_OPEN: "ADD_MOVIE_OPEN",
    ADD_MOVIE_CLOSE: "ADD_MOVIE_CLOSE",
}

export {
    ModalType
}
