const MovieType = {
  GET_MOVIE_START: 'GET_MOVIE_START',
  GET_MOVIE_DONE: 'GET_MOVIE_DONE',
  GET_MOVIE_FAIL: 'GET_MOVIE_FAIL',

  ADD_MOVIE_START: 'ADD_MOVIE_START',
  ADD_MOVIE_DONE: 'ADD_MOVIE_DONE',
  ADD_MOVIE_FAIL: 'ADD_MOVIE_FAIL',

  EDIT_MOVIE_START: 'EDIT_MOVIE_START',
  EDIT_MOVIE_DONE: 'EDIT_MOVIE_DONE',
  EDIT_MOVIE_FAIL: 'EDIT_MOVIE_FAIL',

  DELETE_MOVIE_START: 'DELETE_MOVIE_START',
  DELETE_MOVIE_DONE: 'DELETE_MOVIE_DONE',
  DELETE_MOVIE_FAIL: 'DELETE_MOVIE_FAIL',

  ADD_MOVIE_POSTER_START: 'ADD_MOVIE_POSTER_START',
  ADD_MOVIE_POSTER_DONE: 'ADD_MOVIE_POSTER_DONE',
  ADD_MOVIE_POSTER_FAIL: 'ADD_MOVIE_POSTER_FAIL',
};

export { MovieType };
